--event命名规则
--edit by 孙多良·小浪
--2008.02.20
--因为活动积累过多,event文件夹内文件过多,分类不清晰,
--而且活动拼命和英文混用,现制定规则:
--以后编写脚本,按相应文件夹放置

--活动命名规则	旧脚本不改动,新加脚本按以下命名规则进行.		
--			
--阳历节日-"后缀为jieri_,方便分类,列表对齐查找,方便输入名字查找"		
--时间					节日																				命名
--1月1日				元旦(New Year's Day)								yuandan_jieri
--2月14日				情人节(Valentine's Day)								qingren_jieri	
--3月8日				国际妇女节(International Women' Day)				funv_jieri	
--3月12日				中国植树节(China Arbor Day)							zhishu_jieri	
--4月5日				清明节（Tomb-sweeping Day)							qingming_jieri	
--5月1日				国际劳动节(International Labour Day)				laodong_jieri	
--9月10日				中国教师节(Teacher's Day)							jiaoshi_jieri	
--10月1日				中华人民共和国国庆节(National Day)					guoqing_jieri	
--12月25日				圣诞节(Christmas Day)								shengdan_jieri	
--农历节日-		
--农历正月初一	春节(the Spring Festival)									chunjie_jieri	
--农历正月十五	元宵节(Lantern Festival)									yuanxiao_jieri	
--农历五月初五	端午节(the Dragon-Boat Festival)							duanwu_jieri	
--农历七月初七	乞巧节(中国情人节）(Double-Seventh Day)						qixi_jieri	
--农历八月十五	中秋节(the Mid-Autumn Festival)								zhongqiu_jieri	
--农历九月初九	重阳节(the Double Ninth Festival)							chongyang_jieri	
--农历腊月初八	腊八节(the laba Rice Porridge Festival)						laba_jieri	
--
--总体规则			
--命名规则	event\节日命名\年月\活动脚本	例子:2008年元旦活动脚本.	event\yuandan_jieri\200801\
